SELECT
dfa.[DFA_ROUTECODE].CODE AS Routecode,
dfa.[DFA_ROUTECODE].OMSCHRIJVING AS Routebeschrijving,
dfa.[DFA_ROUTECODE].[IND_ACTIEF] AS RouteActief,
dfa.[WMS_GEBRCODE].[GEBR_OMS] AS Budgethouder,
dfa.[WMS_GEBRCODE].INDACTIEF AS BudgethouderActief,
dfa.[DFA_ROUTECODE].HELPTEXT,
dfa.[WMS_FUNCTIECODE].FUNCTIECODE AS Functiecode,
dfa.[WMS_FUNCTIECODE].[FUNCTIE_OMS] AS FunctiecodeOmschrijving,
dfa.[WMS_FUNCTIECODE].INDACTIEF AS FunctiecodeActief
FROM
dfa.[DFA_ROUTECODE]
JOIN dfa.[DFA_ROUTE_GEBR]
ON dfa.[DFA_ROUTECODE].CODE = dfa.[DFA_ROUTE_GEBR].CODE 
JOIN dfa.[WMS_GEBRCODE]
ON dfa.[DFA_ROUTE_GEBR].GEBRCODE = dfa.[WMS_GEBRCODE].GEBRCODE 
LEFT JOIN dfa.[DFA_ADMINISTRATIE]
ON dfa.[DFA_ROUTE_GEBR].[EXVD_ALF_02] = dfa.[DFA_ADMINISTRATIE].CODE 
LEFT JOIN dfa.[WMS_FUNCTIECODE]
ON dfa.[WMS_FUNCTIECODE].FUNCTIECODE = dfa.[DFA_ROUTE_GEBR].FUNCTIECODE