SELECT
  DOCM.INBOEKER,
  ADMI.CODE AS Divisie,
  ADMI.OMSCHRIJVING AS Administratie,
  DOCM.DOCUMENTNR,
  WREL.CODE AS RelatieCode,
  WREL.NAAM AS RelatieNaam,
  DOCM.EXTERNE_REFERENTIE AS ExterneReferentie,
  DOCM.OMSCHRIJVING AS FactuurOmschrijving,
  DOCM.DOCUMENTDATUM AS Factuurdatum,
  WSTP.STAPNR AS STAPNR,
  DATEDIFF(dd, WSTP.DDINGANG, getdate()) AS DagenBudgethouder,
  CAST(DOCM.DOCUMENTDATUM - getdate() as int) +
    (
      CASE
        WHEN WREL.BETAALTERMIJN = 'GR' then 50
        ELSE WREL.BETAALTERMIJN
      END
    ) AS ResteertDagen,
  WGBR.GEBR_OMS AS GEBRUIKER,
  DOCM.BRUTOBEDRAG,
  DOCM.BTWBEDRAG


/*
  WSTP.DDRAPPEL DDRAPPEL,
  WSTP.GEBRCODE GEBRCODE,
  WSTP.INDSTATUS INDSTATUS,
  WIMP.OBJECTCODE WIMP_OBJECTCODE,
  WIMP.OBJECT_KEY WIMP_OBJECT_KEY,
  WSST.STAP_OMS STAP_OMS,
  WSTP.DDINGANG DDINGANG,
  WSST.FORMNAAM SCHERM,
  WSTP.INDURGENT URGENT,
  WSST.PROCCODE PROCCODE,
  WSST.STAPCODE STAPCODE,
  WPRC.OBJECT_KEY SLEUTEL,
  DOCM.DOCUMENTNR,
	DOCM.ID_ADMINISTRATIE,
  DOCM.ID_DAGBOEK,
  DOCM.DOCUMENTNUMMER_BACKOFFICE,
  DOCM.DOCUMENTDATUM,
  DOCM.ID_RELATIE,
  DOCM.EXTERNE_REFERENTIE,
  DOCM.OMSCHRIJVING,
  DOCM.VERVALDATUM,
  DOCM.ID_BTWCODE,
  DOCM.BTWBEDRAG,
  DOCM.NETTOBEDRAG,
  DOCM.ID_VALUTA,
  DOCM.INBOEKDATUM,
  DOCM.JAAR,
  DOCM.ID_PERIODE,
  DOCM.ID_DOCUMENTSOORT,
  DOCM.ID_DOCUMENTTYPE,
  DOCM.DOCUMENTSTATUS,
  DOCM.AFDELING,
  DOCM.BUDGETHOUDER,
  DOCM.CONTROLEUR,
  DOCM.PROCURATIEHOUDER,
  DOCM.MATERIEDESKUNDIGE,
  DOCM.OPMERKING,
  DOCM.DIRECTIE,
  DOCM.IND_BEWAREN_DOCUMENT,
  DOCM.AKK_BUDGETHOUDER,
  DOCM.AKK_CONTROLEUR,
  DOCM.AKK_PROCURATIEHOUDER,
  DOCM.AKK_MATERIEDESKUNDIGE,
  DOCM.AKK_DIRECTIE,
  DOCM.MOTIVATIE_AKKOORD,
  DOCM.IND_AFKEUREN,
  DOCM.IND_CREDITNOTA,
  DOCM.IND_VERWERKT_FA,
  DOCM.ID_CREDITNOTA,
  DOCM.ID_DOCUMENTTYPE_ARCHIEF,
  DOCM.REKENINGNUMMER,
  DOCM.INBOEKER,
  DOCM.ORDERNUMMER,
  ADMI.CODE ADMINISTRATIECODE,
  DOCM.EXVD_ALF_01,
  DOCM.EXVD_ALF_02,
  DOCM.EXVD_ALF_03,
  DOCM.EXVD_ALF_04,
  DOCM.EXVD_ALF_05,
  DOCM.EXVD_ALF_06,
  DOCM.EXVD_ALF_07,
  DOCM.EXVD_ALF_08,
  DOCM.EXVD_ALF_09,
  DOCM.EXVD_ALF_10,
  DOCM.EXVD_ALF_11,
  DOCM.EXVD_ALF_12,
  DOCM.EXVD_ALF_13,
  DOCM.EXVD_ALF_14,
  DOCM.EXVD_ALF_15,
  DOCM.EXVD_NUM_01,
  DOCM.EXVD_NUM_02,
  DOCM.EXVD_NUM_03,
  DOCM.EXVD_NUM_04,
  DOCM.EXVD_NUM_05,
  DOCM.EXVD_NUM_06,
  DOCM.EXVD_NUM_07,
  DOCM.EXVD_NUM_08,
  DOCM.EXVD_NUM_09,
  DOCM.EXVD_NUM_10,
  DOCM.EXVD_DAT_01,
  DOCM.EXVD_DAT_02,
  DOCM.EXVD_DAT_03,
  DOCM.EXVD_DAT_04,
  DOCM.EXVD_DAT_05,
  DOCM.EXVD_DAT_06,
  DOCM.EXVD_DAT_07,
  DOCM.EXVD_DAT_08,
  DOCM.EXVD_DAT_09,
  DOCM.EXVD_DAT_10,
  DOCM.GREKENINGBEDRAG,
  DOCM.BTWBEDRAG_LAAG,
  DOCM.EXVD_INT_01,
  DOCM.EXVD_INT_02,
  DOCM.EXVD_INT_03,
  DOCM.EXVD_INT_04,
  DOCM.EXVD_INT_05,
  DOCM.IND_TRANSITORISCH,
  DOCM.IND_DOSSIER,
  DOCM.EXVD_MEMO_01,
  DOCM.EXVD_MEMO_02,
  DOCM.EXVD_MEMO_03,
  DOCM.EXVD_MEMO_04,
  DOCM.EXVD_MEMO_05,
  DOCM.EMAILSENDER,
  DOCM.EMAILSUBJECT,
  DOCM.EMAILBODY,
  DOCM.EMAILCC,
  DOCM.EMAILDATE,
  DOCM.EMAILRECIPIENTDONAUUSERNAME,
  DOCM.ROUTECODE,
  DOCM.KOERS,
  DOCM.VREEMDBEDRAG,
  DOCM.BETAALTERMIJN,
  WSST.SHOWNOTESPOPUP,
  WSTP.LOCKEDBYGEBRCODE,
  WSTP.LOCKEXPIRESON,
  WSST.SHOWTRAILPOPUP,
  WSST.REMOVEDOCUMENT,

  (
    SELECT
      COUNT(NOTI.DOCUMENTNR)
    FROM
      dfa.DFA_NOTITIE NOTI
    WHERE
      NOTI.DOCUMENTNR = DOCM.DOCUMENTNR
  ) AS AANTALNOTITIES,

  (
    SELECT
      CASE
        WHEN COUNT(F.DOCUMENTNR) = 1 THEN 'J'
        ELSE 'N'
      END AS HASIMAGE
    FROM
      dfa.DFA_DOCFILE F
    WHERE
      F.DOCUMENTNR = DOCM.DOCUMENTNR
  ) AS HASIMAGE */

FROM
  dfa.WMS_IMPULS AS WIMP
  INNER JOIN dfa.WMS_PROCEDURE AS WPRC ON WIMP.IMPULSNR = WPRC.IMPULSNR
  INNER JOIN dfa.WMS_STAP AS WSTP ON WPRC.PROCNR = WSTP.PROCNR AND WSTP.INDSTATUS = 'A'
  INNER JOIN dfa.WMS_SSTAP AS WSST ON WSST.PROCCODE = WSTP.PROCCODE AND WSST.STAPCODE = WSTP.STAPCODE AND WSST.STAPTYPE = 'S'
  INNER JOIN dfa.WMS_GEBRCODE AS WGBR ON WSTP.GEBRCODE = WGBR.GEBRCODE
  INNER JOIN dfa.DFA_DOCUMENT AS DOCM ON DOCM.DOCUMENTNR = WIMP.OBJECT_KEY
  LEFT OUTER JOIN dfa.DFA_RELATIE AS WREL ON DOCM.ID_RELATIE = WREL.ID_RELATIE
  LEFT OUTER JOIN dfa.DFA_ADMINISTRATIE AS ADMI ON DOCM.ID_ADMINISTRATIE = ADMI.ID_ADMINISTRATIE
