SELECT
dfa.[DFA_ADMINISTRATIE].OMSCHRIJVING AS Werkmaatschappij,
dfa.[DFA_RELATIE].NAAM,
dfa.[DFA_ADMINISTRATIE].OMSCHRIJVING,

CAST(dfa.[DFA_DOCUMENT].DOCUMENTDATUM AS DATE) AS Factuurdatum,

case dfa.[DFA_RELATIE].BETAALTERMIJN
	when 'GR' then 50
	else dfa.[DFA_RELATIE].BETAALTERMIJN
end AS ExactBetaaltermijn,

CAST(dfa.[DFA_DOCUMENT].DOCUMENTDATUM +
(case dfa.[DFA_RELATIE].BETAALTERMIJN
when 'GR' then 50
else dfa.[DFA_RELATIE].BETAALTERMIJN
end) AS DATE) AS Vervaldatum,

dfa.[DFA_DOCUMENT].[EXTERNE_REFERENTIE],
dfa.[DFA_DOCUMENT].BRUTOBEDRAG,
dfa.[DFA_DOCUMENT].INBOEKER

-- 1

(SELECT
ROW_NUMBER()
over(ORDER BY dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].ID ASC) AS Rownr,

dfa.[WMS_GEBRCODE].[GEBR_OMS]
/* CAST(dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].CREATIONDATE - DOCNR.DOCUMENTDATUM AS INT) AS Interval,

CAST(DOCNR.DOCUMENTDATUM +
(case dfa.[DFA_RELATIE].BETAALTERMIJN
when 'GR' then 50
else dfa.[DFA_RELATIE].BETAALTERMIJN
end) - dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].CREATIONDATE AS INT) AS Resterend */


FROM
dfa.[DFA_DOCUMENT] AS DOCNR
JOIN dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT]
ON DOCNR.DOCUMENTNR = dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].DOCUMENTNR
JOIN dfa.[WMS_GEBRCODE]
ON dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].GEBRCODE = dfa.[WMS_GEBRCODE].GEBRCODE
JOIN dfa.[DFA_ADMINISTRATIE]
ON DOCNR.[ID_ADMINISTRATIE] = dfa.[DFA_ADMINISTRATIE].[ID_ADMINISTRATIE]
JOIN dfa.[DFA_RELATIE]
ON DOCNR.[ID_RELATIE] = dfa.[DFA_RELATIE].[ID_RELATIE]

where
Rownr = 1 and
dfa.[DFA_DOCUMENT].DOCUMENTNR = DOCNR.DOCUMENTNR) AS Gebruiker







-- 2



-- 3



-- 4



FROM
dfa.[DFA_DOCUMENT]


JOIN dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT]
ON dfa.[DFA_DOCUMENT].DOCUMENTNR = dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].DOCUMENTNR
JOIN dfa.[WMS_GEBRCODE]
ON dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].GEBRCODE = dfa.[WMS_GEBRCODE].GEBRCODE
JOIN dfa.[DFA_ADMINISTRATIE]
ON dfa.[DFA_DOCUMENT].[ID_ADMINISTRATIE] = dfa.[DFA_ADMINISTRATIE].[ID_ADMINISTRATIE]
JOIN dfa.[DFA_RELATIE]
ON dfa.[DFA_DOCUMENT].[ID_RELATIE] = dfa.[DFA_RELATIE].[ID_RELATIE]
WHERE
dfa.[DFA_DOCUMENT].DOCUMENTNR = 6
ORDER BY
dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].ID ASC






/*

SELECT
ROW_NUMBER()
over(ORDER BY dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].ID ASC) AS [Rownr],

dfa.[WMS_GEBRCODE].[GEBR_OMS],
CAST(dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].CREATIONDATE - dfa.[DFA_DOCUMENT].DOCUMENTDATUM AS INT) AS Interval,

CAST(dfa.[DFA_DOCUMENT].DOCUMENTDATUM +
(case dfa.[DFA_RELATIE].BETAALTERMIJN
when 'GR' then 50
else dfa.[DFA_RELATIE].BETAALTERMIJN
end) - dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].CREATIONDATE AS INT) AS Resterend


FROM
dfa.[DFA_DOCUMENT]
JOIN dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT]
ON dfa.[DFA_DOCUMENT].DOCUMENTNR = dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].DOCUMENTNR
JOIN dfa.[WMS_GEBRCODE]
ON dfa.[DFA_SUBSCRIPTION_PROFILE_EVENT].GEBRCODE = dfa.[WMS_GEBRCODE].GEBRCODE
JOIN dfa.[DFA_ADMINISTRATIE]
ON dfa.[DFA_DOCUMENT].[ID_ADMINISTRATIE] = dfa.[DFA_ADMINISTRATIE].[ID_ADMINISTRATIE]
JOIN dfa.[DFA_RELATIE]
ON dfa.[DFA_DOCUMENT].[ID_RELATIE] = dfa.[DFA_RELATIE].[ID_RELATIE]

where dfa.[DFA_DOCUMENT].DOCUMENTNR = 6 and Rownr = 3

*/
